[meta]
title = "私人使用(链接大合集)"
author = "errrr-er"
version = "0.0.0"
license = "CC-BY-NC-ND 4.0"
date = 2024-12-26
update_date = 2024-12-26
desc = "https://github.com/errrr-er/alll/tree/main"
update_Urls = [
  "",
  "https://ghp.ci/"
]

["链接"]
export = true
visible = true

# 提取云
cloud_extra = true
# 云本去重
dictinct = true
# github raw 链接
options_urls = [
  "",
  "https://ghp.ci/"
]