[meta]
title = "中日英魔法大典(整合版)"

["测试"]
export = true
visible = true
aliases = [ "测试2"]
options = [
]

# 提取云
cloud_extra = true
# 云本去重
dictinct = true
# github raw 链接
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/magic/CASTOUTDEVIL.json"
]