[meta]
title = "私人使用(链接大合集)"
author = "errrr-er"
version = "0.0.0"
license = "CC-BY-NC-ND 4.0"
date = 2024-12-26
update_date = 2024-12-26
desc = "https://github.com/errrr-er/alll/tree/main"
update_Urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/personal_all.toml",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/personal_all.toml"
]



["鸣潮"]
export = true
aliases = ["活动"]
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/wuthering.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/wuthering.json"
]



["海豹"]
export = true
aliases = ["手册","分离"]
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/sealdice.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/sealdice.json"
]



["查询"]
export = true
aliases = ["共群"]
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/qq_find.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/qq_find.json"
]