[meta]
title = "私人使用(链接大合集)"
author = "errrr-er"
version = "0.0.0"
license = "CC-BY-NC-ND 4.0"
date = 2025-01-06
update_date = 2024-12-31
desc = "https://github.com/errrr-er/alll/tree/main"
update_Urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/personal_all.toml",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/personal_all.toml"
]

# 鸣潮
  # 鸣潮、油甘
# COD
  # cod
# 缩写
  # 缩写、abb
# 海豹
  # 手册、分离
# QQ
  # 查询、共群



########
# 鸣潮
########



["油甘"]
export = true
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/wuthering_collection.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/wuthering_collection.json"
]



["鸣潮"]
export = true
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/wuthering.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/wuthering.json"
]



########
# COD
########



["cod"]
export = true
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/cod_story.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/cod_story.json"
]



########
# 缩写
########



["缩写"]
export = true
aliases = ["abb"]
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/abbreviation.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/abbreviation.json"
]



########
# 海豹
########



["手册"]
export = true
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/sealdice_guide.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/sealdice_guide.json"
]



["分离"]
export = true
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/sealdice_lagrange.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/sealdice_lagrange.json"
]



########
# QQ
########



["查询"]
export = true
aliases = ["共群"]
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/qq_find.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/personal/links/qq_find.json"
]