[meta]
title = "KP群汇总"
author = "3987681449"
version = "1.0.0"
license = "CC-BY-NC-SA 4.0"
date = 2025-05-11
update_date = 2025-5-11
desc = "https://github.com/errrr-er/alll/tree/main"
update_Urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/call_of_cthulhu/kp/z_kp_all.toml",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/call_of_cthulhu/kp/z_kp_all.toml"
]

["kp群"]
export = true
options = ["[CQ:image,file=https://github.com/errrr-er/alll/blob/main/call_of_cthulhu/kp/kp.jpg?raw=true,type=show]"]