[meta]
title = "模组资料(图片)"
author = "3987681449 更新时记得在release下载最新版本对应deck包"
version = "1.0.0"
license = "CC-BY-NC-SA 4.0"
date = 2025-04-08
update_date = 2025-04-08
desc = "https://github.com/errrr-er/alll/tree/main"
update_Urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/call_of_cthulhu/picture/picture_all.toml",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/call_of_cthulhu/picture/picture_all.toml"
]

["phelp"]
export = true
visible = true
options = [""]


# 月光舞鞋
["西大附中"]
export = true
options = ["[图:./_pic.deck/pic/月光舞鞋/西大附中.png]"]


# 望君长留
["爱良"]
export = true
options = ["[图:./_pic.deck/pic/望君长留/爱良.png]"]

["釜村徹"]
export = true
options = ["[图:./_pic.deck/pic/望君长留/釜村徹.png]"]

["釜村一家"]
export = true
options = ["[图:./_pic.deck/pic/望君长留/釜村一家.png]"]


# 幽暗之门
["幽暗预设"]
export = true
options = ["[图:./_pic.deck/pic/幽暗之门/幽暗预设1.png]\f[图:./_pic.deck/pic/幽暗之门/幽暗预设2.png]\f[图:./_pic.deck/pic/幽暗之门/幽暗预设3.png]\f[图:./_pic.deck/pic/幽暗之门/幽暗预设4.png]\f[图:./_pic.deck/pic/幽暗之门/幽暗预设5.png]\f[图:./_pic.deck/pic/幽暗之门/幽暗预设6.png]\f[图:./_pic.deck/pic/幽暗之门/幽暗预设7.png]\f[图:./_pic.deck/pic/幽暗之门/幽暗预设8.png]\f[图:./_pic.deck/pic/幽暗之门/幽暗预设9.png]\f[图:./_pic.deck/pic/幽暗之门/幽暗预设10.png]"]


# 你就刚刚好
[""]
export = true
options = [""]


#夏洛克福尔摩斯症候群
[""]
export = true
options = [""]
