[meta]
title = "模组资料(图片)"
author = "裗浳(3612464276)"
version = "1.0.0"
license = "CC-BY-NC-SA 4.0"
date = 2025-04-08
update_date = 2025-04-08
desc = "https://github.com/errrr-er/alll/tree/main"
update_Urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/call_of_cthulhu/picture/z_picture_all.toml",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/call_of_cthulhu/picture/z_picture_all.toml"
]

["phelp"]
export = true
visible = true

# 提取云
cloud_extra = true
# 云本去重
dictinct = true
# github raw 链接
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/call_of_cthulhu/magic/CJE/magic.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/call_of_cthulhu/magic/CJE/magic.json"
]





[""]
export = true
aliases = ["","",""]
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/call_of_cthulhu/picture/all/.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/call_of_cthulhu/picture/all/.json"
]





