[meta]
title = "私人使用"
author = "errrr-er"
version = "0.0.0"
license = "CC-BY-NC-ND 4.0"
date = 2024-12-26
update_date = 2025-01-29
desc = "https://github.com/errrr-er/personal"
update_Urls = [
  "https:https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/personal_all.toml",
  "https://ghp.ci/https:https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/personal_all.toml"
]



########
# 海豹
########



["手册"]
export = true
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/dice_setting/response_link/sealdice_guide.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/dice_setting/response_link/sealdice_guide.json"
]



["分离"]
export = true
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/dice_setting/response_link/sealdice_lagrange.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/dice_setting/response_link/sealdice_lagrange.json"
]



["猫回复"]
export = true
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/dice_setting/response_link/sealdice_reply.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/dice_setting/response_link/sealdice_reply.json"
]



["猫翻译"]
export = true
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/dice_setting/response_link/sealdice_translate.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/dice_setting/response_link/sealdice_translate.json"
]



["猫discord"]
export = true
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/dice_setting/response_link/sealdice_discord.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/dice_setting/response_link/sealdice_discord.json"
]



["猫zip"]
export = true
options = []
cloud_extra = true
dictinct = true
options_urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/dice_setting/response_link/sealdice_zip.json",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/other/cat_toml/dice_setting/response_link/sealdice_zip.json"
]