[meta]
title = "怪锤(日中对应)"
author = "3987681449"
version = "1.0.0"
license = "CC-BY-NC-SA 4.0"
date = 2025-05-08
update_date = 2025-5-08
desc = "https://github.com/errrr-er/alll/tree/main"
update_Urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/call_of_cthulhu/malleus/z_malleus_all.toml",
  "https://ghfast.top/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/call_of_cthulhu/malleus/z_malleus_all.toml"
]

["サイメイギ"]
export = true
options = ["塞梅格里"]