[meta]
title = "旧版手册呪文(三语对照)"
author = "裗浳(3612464276)"
version = "1.0.0"
license = "CC-BY-NC-SA 4.0"
date = 2024-06-23
update_date = 2024-12-19
desc = "https://github.com/errrr-er/alll/tree/main"
update_Urls = [
  "https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/magic/CJE/magic_all.toml",
  "https://ghp.ci/https://raw.githubusercontent.com/errrr-er/alll/refs/heads/main/magic/CJE/magic_all.toml"
]
